

---
title: 'Homework: Setup and Warm-up'
output:
  html_notebook: 
    code_folding: none
    highlight: textmate
---


```{r setup, echo=FALSE}
rm(list = ls())
path_to_script <- dirname(rstudioapi::getActiveDocumentContext()$path) 
  # assuming you are using RStudio
required_packages <- c()
for (pkg in required_packages) {
  if (!(pkg %in% rownames(installed.packages()))) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}

knitr::opts_chunk$set(echo = TRUE)
```


# Exercise 0: Setting up Git and Github

## Part 1: Command line interface 

Set up your Git and Github. 
You can find many resources regarding this online, including [a guide from Github](https://docs.github.com/en/get-started/quickstart/set-up-git).
Another nice one is Karl Broman's [minimal git/github tutorial](https://kbroman.org/github_tutorial/).

In this course, you will be mainly interacting with Git through its command-line interface. 
(In particular, I am not going to help you if you get yourself into troubly by using a Git GUI, like the RStudio one.)
If you are on Windows, you can use [Git Bash](https://www.atlassian.com/git/tutorials/git-bash). 
If you are on Mac, I recommend you use [iTerm2](https://iterm2.com/) instead of the built-in Terminal. 
If you are on Linux, most likely you don't need my suggestions :-)

Besides the bare minimum Git set-up, I recommend you also set up the default editor and visual diff tool. 
I personally use Sublime Text as the Git editor on macOS and, for those on Windows, Notepad++ is one popular option. As for visual diff, I like [Meld](https://meldmerge.org/).
The following commands tell Git to use Sublime and Meld:

```{bash, eval=FALSE}
git config --global core.editor subl --wait
git config --global diff.tool meld
git config --global --add difftool.prompt false
```

(Incidentally, all the above commands do is to simply modify the "global" `.gitconfig` file, typically located in your home directory. You can find the exact location of this file is via the command `git config --list --show-origin`. Note, though, that the `--show-origin` option won't work on JHPCE, which has an old 2013 version of Git.)

## Part 2: Graphical user interface

While I've just told you to use the command-line to interact with Git, a Git GUI can be a valuable tool for visually examining the current and past states of a repo.
So, my recommended workflow is to interact with Git via command-line (b/c it gives you more precise controls) but to use a GUI for visualizing the repo. 
I personally have been a happy user of a cross-platform [GitKraken](https://www.gitkraken.com/), which is freely available via [GitHub Student Developer Pack](https://education.github.com/pack/). 
But other freeware like [Github Desktop](https://desktop.github.com/) should work fine for the intended use of simply visualizing the repo. 

## Things to commit and submit

None



# Exercise 1: Playing around with command-line and Git

Log in to JHPCE and `qrsh` into a compute node. 
For this exercise, we use the `homework/git_experiment` folder from the course repository, so clone the repo to your JHPCE home directory:

```{bash, eval=FALSE}
git clone https://github.com/aki-nishimura/stats-comp-algo-software-2023
```

Next, go into the `git_experiment` folder, initialize it as a git repo (yes, you can have a git repo within another git repo), and commit `foo.tex`:

```{bash, eval=FALSE}
git init
git add foo.tex
git commit -m "TeX file for experiment" 
```

Then try compiling the tex file via command-line, which can be done via:

```{bash, eval=FALSE}
module load tex
pdflatex foo.tex
``` 

You can suppress the compilation messages by redirecting the `stderr` and `stdout` to `/dev/null`:
```{bash, eval=FALSE}
pdflatex foo.tex > /dev/null 2>&1
```

For the rest of this exercise, you use a "stream" editor _sed_. 
A stream editor processes a text file line-by-line, without ever loading the entire file into memory. 
This is useful when, for example, you are processing a massive text file containing data and you cannot load it to R with `read.table()`.
Using `sed` to edit a tex file is, obviously, an overkill and done here only for demonstration purposes.

The following command demonstrates how to add a line to a text file using `sed`: 

```{bash, eval=FALSE}
linenum=10
sed -i "$linenum i This is the first sentence." foo.tex
```

Check the change via `git diff`. After doing so, go ahead and add this change to the repo:

```{bash, eval=FALSE}
git add -u
git commit -m "Add first sentence to TeX file"
```

Now write a bash script which repeats the following cycle of steps for 99 times: adds a new sentence to `foo.tex`, compile it, and commit *both* the TeX source file and its PDF output. I've provided starter code `edit_and_commit.sh` for this exercise. Once you have the bash script, execute it and check the disk space usage of the `git_experiement` folder. You can do this via `du -h -s git_experiment/` (`-h` for "human-readable" and `-s` for "summarize"). 

**Question:** Does the size of the folder look reasonable relative to the sizes of the individual files inside it? (Use `ls -l -h` to list the files with the size info; `-l` is for "long.") If not, why would that be? How would this explain why [Github discourages you from commiting (large) binary files](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github)?

**Your answer:** (To be filled.)

## Things to commit and submit

1. Completed `edit_and_commit.sh`
2. Answer to the question above



# Exercise 2: Setting up an R package skeleton

Set up your own version of the `hiperglm` package as we discussed in the class and put it up on your Github. The package set-up should have/include

* Proper R package structure; i.e. you can install it via `R CMD build/install`.
* MIT licence.
* Exported function `hiper_glm(design, outcome)` for model fitting.
* Exported S3 methods `coef`, `vcov`, and `print`.
* Clean and modular git history.

## Things to commit and submit

Hyperlink to the `hiperglm` repository on your Github account